config/routes.rb
Rails.application.routes.draw do
  root "topics#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
#resources :posts
  resources :topics do
    resources :posts do
      post 'read', on: :member
      resources :comments, except: [:index, :show]
      resources :tags
      resources :ratings
    end
  end
  resources :tags
  get '/posts' => 'posts#index'
  #shallow: true means only: [:index, :new, :create]
  resources :insides
  resources :articles do
    resources :insides
  end
  resources :books
  resources :high_scores
  get 'greetings/hello'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    #can :read, Post, public: true
    user ||=User.new #guest user(not logged in)
    if user.admin?
      can :manage, :all
    else user.present?
      can :manage, Post, user_id: user.id
      can :manage, Comment, user_id: user.id
      can :read, :all
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :insides, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/bouncer.rb
# frozen_string_literal: true
class Bouncer
  def bounce(bouncee)
    Math.sqrt(bouncee)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user
end

app/models/high_score.rb
class HighScore < ApplicationRecord
end

app/models/inside.rb
class Inside < ApplicationRecord
  belongs_to :article
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  has_many :comments, dependent: :destroy
  has_many :posttags, dependent: :destroy
  has_many :tags, through: :posttags
  has_many :ratings, dependent: :destroy
  accepts_nested_attributes_for :tags, reject_if: :all_blank
  has_one_attached :image, dependent: :destroy
  belongs_to :user
  has_and_belongs_to_many :users, join_table: 'posts_users_read_status'

  scope :date_between,->(start_date,end_date) { where(created_at: start_date..end_date)}
  #validations
  validates :name, presence: true
  validates :name, length: { maximum: 20}
  validates :name, uniqueness: {message: "already exists"}

end

app/models/posttag.rb
class Posttag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/rating.rb
class Rating < ApplicationRecord
  after_save :update_rating
  belongs_to :post

  def update_rating
    self.post.update(rating_average: self.post.ratings.average(:num))
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :posttags, dependent: :destroy
  has_many :posts, through: :posttags
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, through: :posts, dependent: :destroy
  has_many :ratings, through: :posts, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email
  def send_welcome_email
    # UserMailer.welcome(self).deliver_now
    SignUpMailJob.perform_later(self)
  end
  has_many :posts
  has_many :comments
  has_and_belongs_to_many :posts, join_table: 'posts_users_read_status'


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
    # @topics=Topic.includes(:posts)
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:title, :content)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/insides_helper.rb
module InsidesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <% if topic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, style: "display: block", class: "form-label" %>
    <div class="col-sm-5"><%= form.text_field :title , class: "form-control"%></div>
  </div>

  <div class="mb-3">
    <%= form.label :content, style: "display: block", class: "form-label" %>
    <div class="col-sm-5"><%= form.text_area :content, class: "form-control" %></div>
  </div>

  <div class="actions">
    <%= form.submit  class: "btn btn-success" %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div id="<%= dom_id topic %>">
  <div class="card">
    <div class="card-body">

      <h5 class="card-title"><%= topic.title %></h5>

      <p class="card-text"><%= topic.content %></p>

    <% if @topic.nil? %><%= link_to "Show this topic", topic, class: "btn btn-secondary" %><% end %>
    <%= link_to "Show this post", topic_posts_path(topic), class: "btn btn-primary" %>

    </div>
  </div><br>
</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Show this topic", @topic, class: "btn btn-primary" %>
  <%= link_to "Back to topics", topics_path, class: "btn btn-secondary" %>
</div>

app/views/topics/index.html.erb
<!--<p style="color: green"><%#= notice %></p>-->

<h1>Topics</h1>

<div id="topics">
  <% @topics.each do |topic| %>
    <%= render topic %>
  <% end %>

  <%= link_to "New topic", new_topic_path , class: "btn btn-success"%>

</div>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render "form", topic: @topic %>
<br>

<div>
  <%= link_to "Back to topics", topics_path , class: "btn btn-secondary"%>
</div>

app/views/topics/show.html.erb
<!--<p style="color: green"><%#= notice %></p>-->

<%= render @topic %>

<div>
  <%= link_to "Back to topics", topics_path, class: "btn btn-secondary" %>
  <%= link_to "Edit this topic", edit_topic_path(@topic) , class: "btn btn-warning"%>
  <%= link_to "Destroy this topic", topic_path(@topic), method: :delete, data: { turbo_method: "delete", turbo_confirm: "Are you sure?" }, class: "btn btn-danger"%>
</div>