config/routes.rb
Rails.application.routes.draw do
  root "topics#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
#resources :posts
  resources :topics do
    resources :posts do
      post 'read', on: :member
      resources :comments, except: [:index, :show]
      resources :tags
      resources :ratings
    end
  end
  resources :tags
  get '/posts' => 'posts#index'
  #shallow: true means only: [:index, :new, :create]
  resources :insides
  resources :articles do
    resources :insides
  end
  resources :books
  resources :high_scores
  get 'greetings/hello'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    #can :read, Post, public: true
    user ||=User.new #guest user(not logged in)
    if user.admin?
      can :manage, :all
    else user.present?
      can :manage, Post, user_id: user.id
      can :manage, Comment, user_id: user.id
      can :read, :all
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :insides, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/bouncer.rb
# frozen_string_literal: true
class Bouncer
  def bounce(bouncee)
    Math.sqrt(bouncee)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user
end

app/models/high_score.rb
class HighScore < ApplicationRecord
end

app/models/inside.rb
class Inside < ApplicationRecord
  belongs_to :article
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  has_many :comments, dependent: :destroy
  has_many :posttags, dependent: :destroy
  has_many :tags, through: :posttags
  has_many :ratings, dependent: :destroy
  accepts_nested_attributes_for :tags, reject_if: :all_blank
  has_one_attached :image, dependent: :destroy
  belongs_to :user
  has_and_belongs_to_many :users, join_table: 'posts_users_read_status'

  scope :date_between,->(start_date,end_date) { where(created_at: start_date..end_date)}
  #validations
  validates :name, presence: true
  validates :name, length: { maximum: 20}
  validates :name, uniqueness: {message: "already exists"}

end

app/models/posttag.rb
class Posttag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/rating.rb
class Rating < ApplicationRecord
  after_save :update_rating
  belongs_to :post

  def update_rating
    self.post.update(rating_average: self.post.ratings.average(:num))
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :posttags, dependent: :destroy
  has_many :posts, through: :posttags
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, through: :posts, dependent: :destroy
  has_many :ratings, through: :posts, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email
  def send_welcome_email
    # UserMailer.welcome(self).deliver_now
    SignUpMailJob.perform_later(self)
  end
  has_many :posts
  has_many :comments
  has_and_belongs_to_many :posts, join_table: 'posts_users_read_status'


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/insides_controller.rb
class InsidesController < ApplicationController
  before_action :set_article
  before_action :set_inside, only: %i[ show edit update destroy ]

  def index
    @insides=@article.insides
    #@insides=inside.all
  end

  def new
    @inside=@article.insides.build
    #@inside=inside.new
  end

  def show
  end

  def create
    @inside = @article.insides.build(inside_params)
    if @inside.save
      flash[:notice]= "Inside was successfully created."
      redirect_to [@article, @inside]
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit

  end
  def update
    if @inside.update(inside_params)
      redirect_to [@article, @inside], notice: "Inside was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @inside.destroy
    redirect_to [@article, :insides], notice: "Inside was successfully destroyed."
  end
  private
  def set_article
    @article = Article.find(params[:article_id])
  end
  def set_inside
    @inside=@article.insides.find(params[:id])
  end

  def inside_params
    params.require(:inside).permit(:commenter, :body, :article_id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/insides_helper.rb
module InsidesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/insides/_form.html.erb
<%= form_with(model: [@article, inside]) do |form| %>
  <!--form_with(model: [@topic, post])-->
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/insides/_inside.html.erb
<div id="<%= dom_id inside %>">
  <p>
    <strong>Commenter:</strong>
    <%= inside.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= inside.body %>
  </p>
</div>

app/views/insides/edit.html.erb
<h1>Edit Inside</h1>

<%= render "form", inside: @inside %>

<br>

<div>
  <%= link_to "Show this post", [@article, @inside] %> |
  <%= link_to "Back to insides", article_insides_path(@article) %>
</div>

app/views/insides/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Insides</h1>


<% @insides.each do |inside| %>
  <%= render inside %>
  <p>
    <%= link_to "show this inside", [@article, inside] %>
  </p>
<% end %>
<br>
<%= link_to "Back to articles", articles_path %> |
<%= link_to "New inside", new_article_inside_path %>

app/views/insides/new.html.erb
<h1>New Inside</h1>

<%= render "form", inside: @inside %>
<br>

<div>
  <%= link_to "Back to insides", article_insides_path(@article) %>
</div>

app/views/insides/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @inside %>

<div>
  <%= link_to "Edit this inside", edit_article_inside_path([@article, @inside]) %> |
  <%= link_to "Back to inside", [@article, :insides] %>
<br><br>
  <%= button_to "Destroy this post", [@article, @inside], method: :delete %>