config/routes.rb
Rails.application.routes.draw do
  root "topics#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
#resources :posts
  resources :topics do
    resources :posts do
      post 'read', on: :member
      resources :comments, except: [:index, :show]
      resources :tags
      resources :ratings
    end
  end
  resources :tags
  get '/posts' => 'posts#index'
  #shallow: true means only: [:index, :new, :create]
  resources :insides
  resources :articles do
    resources :insides
  end
  resources :books
  resources :high_scores
  get 'greetings/hello'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    #can :read, Post, public: true
    user ||=User.new #guest user(not logged in)
    if user.admin?
      can :manage, :all
    else user.present?
      can :manage, Post, user_id: user.id
      can :manage, Comment, user_id: user.id
      can :read, :all
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :insides, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/bouncer.rb
# frozen_string_literal: true
class Bouncer
  def bounce(bouncee)
    Math.sqrt(bouncee)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user
end

app/models/high_score.rb
class HighScore < ApplicationRecord
end

app/models/inside.rb
class Inside < ApplicationRecord
  belongs_to :article
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  has_many :comments, dependent: :destroy
  has_many :posttags, dependent: :destroy
  has_many :tags, through: :posttags
  has_many :ratings, dependent: :destroy
  accepts_nested_attributes_for :tags, reject_if: :all_blank
  has_one_attached :image, dependent: :destroy
  belongs_to :user
  has_and_belongs_to_many :users, join_table: 'posts_users_read_status'

  scope :date_between,->(start_date,end_date) { where(created_at: start_date..end_date)}
  #validations
  validates :name, presence: true
  validates :name, length: { maximum: 20}
  validates :name, uniqueness: {message: "already exists"}

end

app/models/posttag.rb
class Posttag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/rating.rb
class Rating < ApplicationRecord
  after_save :update_rating
  belongs_to :post

  def update_rating
    self.post.update(rating_average: self.post.ratings.average(:num))
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :posttags, dependent: :destroy
  has_many :posts, through: :posttags
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, through: :posts, dependent: :destroy
  has_many :ratings, through: :posts, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email
  def send_welcome_email
    # UserMailer.welcome(self).deliver_now
    SignUpMailJob.perform_later(self)
  end
  has_many :posts
  has_many :comments
  has_and_belongs_to_many :posts, join_table: 'posts_users_read_status'


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :disable_bullet_if_index
  protect_from_forgery except: [:index ,:show, :create, :new]
  before_action :authenticate_user!
  before_action :set_topic
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    if params[:topic_id]
      @posts=@topic.posts.paginate(page: params[:page], per_page: 10).includes([:users])
      # @post = @topic.posts.build
    else
      @start_date= params[:start_date]? Date.parse(params[:start_date]) : Date.yesterday
      @end_date= params[:end_date]? Date.parse(params[:end_date]) : Date.today
      @posts = Post.includes(:topic, :users).date_between(@start_date,@end_date).paginate(page: params[:page], per_page: 6)
    end
  end
  # GET /posts/1 or /posts/1.json
  def show
    @post=@topic.posts.includes(comments: [:user]).find(params[:id])
  end

  # GET /posts/new
  def new
     @post = @topic.posts.build
  end

  # GET /posts/1/edit
  def edit
  end
  # POST /posts or /posts.json
  def create
    @post = @topic.posts.build(post_params)
    @post.user_id=current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to topic_post_path(@topic, @post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to topic_post_path([@topic, @post]), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      if params[:topic_id]
        format.html { redirect_to topic_posts_path(@topic), notice: "Post was successfully destroyed." }
      else
        format.html { redirect_to posts_path, notice: "Post was successfully destroyed." }
      end
      format.json { head :no_content }
    end
  end

  def read
    @post.users << current_user unless @post.users.include?(current_user)
    head :created
  end
  private
    def disable_bullet_if_index
      return unless defined? Bullet
      Bullet.enable = false if params[:action] == "index"
    end
    def set_topic
      @topic= Topic.find(params[:topic_id]) if params[:topic_id]
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = @topic.posts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
        params.require(:post).permit(:name, :publish, :image, :topic_id, :post_id, tags_attributes: [:name],tag_ids: [])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/insides_helper.rb
module InsidesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/posts/_filter_form.html.erb
<%= form_with url: posts_url, method: :get do |form| %>
  <div class="row g-3 align-items-center">
    <div class="col-auto"><%= form.label :From %></div>
    <div class="col-auto"><%= form.date_field :start_date, value: params[:start_date],class: "form-control" %></div>
    <div class="col-auto"><%= form.label :to %></div>
    <div class="col-auto"><%= form.date_field :end_date, value: params[:end_date], class: "form-control" %></div>
    <div class="col-auto"><%= form.submit "Show details", class: "btn btn-success" %></div>
  </div>
<% end %>

app/views/posts/_form.html.erb
<h2>New Post</h2>
<%= form_with(model: [@topic, post], data: {remote: true}) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :name %>
    <div class="col-sm-5"><%= form.text_field :name, class: "form-control" %></div>
  </div>
  <div class="mb-3">
    <%= form.label :publish %>
    <div class="col-sm-5"><%= form.date_field :publish, class: "form-control"  %></div>
  </div>
  <div class="mb-3">
    <%= form.label :image %>
    <div class="col-sm-5"><%= form.file_field :image ,class: "form-control",type: "file", id: "formFile"%></div>
  </div>
  <div class="mb-3">
    <%= form.label :tag_name %>
    <div class="col-sm-5"><%= form.fields_for :tags,@post.tags.build do |field| %>
      <%= field.text_field :name, class: "form-control"  %>
      <% end %></div>
  </div>

  <div class="mb-3">
    <%= form.label :All_tags %>
    <div class="col-sm-5"><%= form.collection_select :tag_ids,Tag.all,:id,:name,{},{:multiple => true, class: "form-control tag_name"} %></div>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-success"%>
  </div><br>
<% end %>

app/views/posts/_post.html.erb
<tr>
<td><%= post.name %>&nbsp</td>
<td><%= (post.rating_average || 0.0).floor(1) %></td>
<td><%= post.comments_count %> comments</td>
<td><%= post.users.include?(current_user)? 'Read' : 'Unread' %></td>
<td><%= link_to "Show", topic_post_path(post.topic, post), class:"btn btn-info" %></td>
<% if can? :destroy, post %>
<!--  <td><%#= link_to "Destroy", topic_post_path(post.topic,post), data: { turbo_method: "delete", turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %></td>-->
    <td><%= link_to "Destroy", topic_post_path(post.topic,post),method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-danger" %></td>
<% else %>
  <td></td>
<% end %>
</tr>

app/views/posts/create.js.erb
<% if @post.errors.any? %>
  document.getElementById('new_form').innerHTML=("<%= escape_javascript(render partial: 'posts/form', locals:  { post: @post}) %>");
<% else %>
  document.getElementById('new_form').innerHTML="";
  document.getElementById('table-body').innerHTML +=("<%= escape_javascript(render partial: 'posts/post', locals:  { post: @post}) %>");
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>
<% if params[:topic_id] %>
<div>
  <%= link_to "Back", topic_post_path([@topic, @post]) , class: "btn btn-secondary" %>
</div>
<% else %>
  <div>
    <%= link_to "Show this post", @post %> |
    <%= link_to "Back to posts", posts_path %>
  </div>
<% end %>
<p></p>

app/views/posts/index.html.erb
<h1>Posts</h1>
<% if @topic.nil? %>
  <%= render "filter_form" %>
<% end %>
<br>
<table class="table table-dark table-striped table-hover">
    <thead>
    <tr>
      <th>Name</th>
      <th>Average Rating</th>
      <th>Comments</th>
      <th>Status</th>
      <th colspan="2"> Actions</th>
    </tr>
    </thead>
    <tbody id="table-body">
        <%= render @posts %>
    </tbody>
</table>
<% if @topic.present? %>
  <%= link_to "Back to topic", topic_path(@topic), class: "btn btn-secondary" %>
  <%= link_to "New post", new_topic_post_path(@topic), remote: true, class: "btn btn-success" %>
<% end %>
<br><br>
<div id="new_form"></div>
<br><br>
<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
<p></p>

app/views/posts/new.html.erb
<%= render "form", post: @post %>

<div>
  <%= link_to "Back to post", topic_posts_path(@topic), class: "btn btn-secondary"  %>
</div>

app/views/posts/new.js.erb
document.getElementById('new_form').innerHTML = ("<%= escape_javascript(render partial: 'posts/form', locals: { post: @post} ) %>");

app/views/posts/show.html.erb
<% content_for :head do %>
  <% unless @post.users.include?(current_user) %>
    <%= javascript_pack_tag 'post', 'data-turbolinks-track': 'reload', defer: true %>
  <% end %>
<% end %>
<div id="post" data-read-url="<%= read_topic_post_path(@topic, @post) %>">
<div class="card" style="width: 25rem;">
  <% if @post.image.attached? %>
    <div class="card-img-top"><%= image_tag(@post.image,style:"width:400px;height:400px")%></div>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= @post.name %></h5>
    <%= @post.publish %>
    <%= @post.user.email %>
    <p class="card-text"></p>
    <% if can? :destroy, @post %>
      <%= link_to "Edit this post", edit_topic_post_path([@topic, @post]), class: "btn btn-warning"  %>
      <%#= link_to "Destroy", topic_post_path(@topic,@post), data: { turbo_method: "delete", turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
      <%= link_to "Destroy", topic_post_path(@topic,@post),method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-danger" %>
    <% end %>
  </div>
</div>
<br>
<h3>Comments</h3>

<% @post.comments.each do |comment| %>
<%= render comment %>
<% end %>

<% if @post.tags.length>0 %>
  <strong>Tags:</strong>
  <% @post.tags.each do |tag| %>
    <%= link_to tag_path, style:"text-decoration:none" , class: "btn btn-primary" do %>
      <span class="tag"><%= tag.name %></span>
    <% end %>
  <% end %>
<% end %>
<br><br>
<table><tr>
  <%= form_with(model: [@topic, @post]) do |f| %>
    <td><%= f.fields_for :tags,@post.tags.build do |field| %>
      <%= field.label "New Tag" %>
    <div class="col-sm-10"><%= field.text_field :name, class: "form-control" %></div>
    <% end %></td>
    <td>
    <%= f.label "Tags" %>
<!--    <div class="col-sm-5"><%#= f.collection_select :tag_ids,Tag.all,:id,:name,{},{multiple: true, class: "form-control"}%></div><br>-->
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Select tags
      </button>
<!--      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">-->
        <%= f.collection_select(:tag_ids,Tag.all,:id,:name,{},{multiple: true, class: 'form-control dropdown-menu'}) %>
<!--      </div>-->
    </div>
    </td>
    <td><br>&nbsp;&nbsp;<%= f.submit "Add", class: "btn btn-success" %></td>
  <% end %>
</tr></table><br>

<strong>Rating:</strong><br><br>
<% (1..5).each do |t| %>
  <%= t %> Star
  <% y=@post.ratings.group(:num).where(num: t).size %>
  <% y=y.delete(t) %>=
  <% if y.is_a? Numeric  %>
    <%= y %>
  <% else %>
    <%= "0" %>
  <% end %><br>
<% end %>
<br>
<div class="field">
<%= form_with model: [@topic,@post,@post.ratings.build] do |f| %>
    <strong>Give Rating to the Post:</strong>
      <%= f.radio_button :num, 1 %>1
      <%= f.radio_button :num, 2 %>2
      <%= f.radio_button :num, 3 %>3
      <%= f.radio_button :num, 4 %>4
      <%= f.radio_button :num, 5 %>5
  <%= f.submit "Rate", class: 'btn btn-primary' %>
<% end %>
</div>
<br>

  <%= link_to "New Comment", new_topic_post_comment_path(@topic,@post), class: "btn btn-success" %>
  <%= link_to "Back to post", topic_posts_path(@topic), class: "btn btn-secondary"  %>

<p></p>
</div>